/*
 * Copyright (c) 2024. Devtron Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// appId: 80, appName: amit-16-jan-replica, 2 workflows, no linked, no external ci, no CI is parent
import { CIBuildType } from '@devtron-labs/devtron-fe-common-lib'

import { DEFAULT_STATUS } from '../../../../../config'
import { CdPipelineResult, CDStage, CiPipelineResult } from '../types'

export const ciConfigResp = {
    code: 200,
    status: 'OK',
    result: {
        id: 77,
        appId: 80,
        dockerRegistry: 'Devtron Playstation',
        dockerRepository: 'test',
        ciBuildConfig: {
            buildPackConfig: null,
            ciBuildType: CIBuildType.SELF_DOCKERFILE_BUILD_TYPE,
            dockerBuildConfig: {
                dockerfileContent: '',
                dockerfileRelativePath: 'Dockerfile',
            },
            gitMaterialId: 80,
        },
        ciPipelines: [
            {
                isManual: true,
                dockerArgs: new Map<string, string>(),
                isExternal: false,
                parentCiPipeline: 0,
                parentAppId: 0,
                externalCiConfig: { id: 0, webhookUrl: '', payload: '', accessKey: '' },
                ciMaterial: [
                    {
                        source: { type: 'SOURCE_TYPE_BRANCH_FIXED', value: 'test' },
                        gitMaterialId: 80,
                        id: 107,
                        gitMaterialName: 'getting-started-nodejs',
                    },
                ],
                name: 'amit-16-jan-replica-ci-arya-test',
                id: 106,
                active: true,
                linkedCount: 0,
                scanEnabled: true,
            },
            {
                isManual: true,
                dockerArgs: new Map<string, string>(),
                isExternal: false,
                parentCiPipeline: 0,
                parentAppId: 0,
                externalCiConfig: { id: 0, webhookUrl: '', payload: '', accessKey: '' },
                ciMaterial: [
                    {
                        source: { type: 'SOURCE_TYPE_BRANCH_FIXED', value: 'master' },
                        gitMaterialId: 80,
                        id: 97,
                        gitMaterialName: 'getting-started-nodejs',
                    },
                ],
                name: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                id: 96,
                active: true,
                linkedCount: 0,
                scanEnabled: false,
            },
        ],
        appName: 'amit-16-jan-replica',
        version: 'test-version',
        materials: [{ gitMaterialId: 80, materialName: 'getting-started-nodejs' }],
        scanEnabled: true,
        appWorkflowId: 77,
        beforeDockerBuild: [],
        afterDockerBuild: [],
    } as CiPipelineResult,
}

export const cdConfigResp = {
    code: 200,
    status: 'OK',
    result: {
        pipelines: [
            {
                id: 79,
                environmentId: 1,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                name: 'amit-16-jan-replica-amit-16-jan-erferf',
                description: 'test',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 80,
                environmentId: 2,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 92,
                environmentId: 3,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-deploy',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 94,
                environmentId: 5,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 95,
                environmentId: 6,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
        ],
        appId: 80,
    } as CdPipelineResult,
}

export const cdConfigPrePostResp = {
    code: 200,
    status: 'OK',
    result: {
        pipelines: [
            {
                id: 92,
                environmentId: 3,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-deploy',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 94,
                environmentId: 5,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 79,
                environmentId: 1,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {
                    status: 'OK',
                    triggerType: 'AUTOMATIC',
                    name: 'Pre-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    beforeStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                postStage: {
                    status: 'OK',
                    triggerType: 'AUTOMATIC',
                    name: 'Post-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    afterStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 80,
                environmentId: 2,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 95,
                environmentId: 6,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
        ],
        appId: 80,
    },
}

export const cdConfigPrePostRespWithPrePostSequential = {
    code: 200,
    status: 'OK',
    result: {
        pipelines: [
            {
                id: 92,
                environmentId: 3,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-deploy',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 94,
                environmentId: 5,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 79,
                environmentId: 1,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    name: 'Pre-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    beforeStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                postStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    name: 'Post-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    afterStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 80,
                environmentId: 2,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    description: 'test',
                    name: 'Pre-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    beforeStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                postStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    name: 'Post-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    afterStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 95,
                environmentId: 6,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    name: 'Pre-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    beforeStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                postStage: {
                    status: DEFAULT_STATUS,
                    triggerType: 'AUTOMATIC',
                    name: 'Post-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    afterStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
        ],
        appId: 80,
    },
}

export const workflow = {
    code: 200,
    status: 'OK',
    result: {
        appId: 80,
        appName: 'amit-16-jan-replica',
        workflows: [
            {
                id: 92,
                name: 'first',
                appId: 80,
                tree: [
                    {
                        id: 172,
                        appWorkflowId: 92,
                        type: 'CI_PIPELINE',
                        componentId: 96,
                        parentId: 0,
                        parentType: '',
                    },
                    {
                        id: 173,
                        appWorkflowId: 92,
                        type: 'CD_PIPELINE',
                        componentId: 79,
                        parentId: 96,
                        parentType: 'CI_PIPELINE',
                    },
                ],
            },
            {
                id: 93,
                name: 'external ci',
                appId: 80,
                tree: [
                    {
                        id: 195,
                        appWorkflowId: 93,
                        type: 'CI_PIPELINE',
                        componentId: 106,
                        parentId: 0,
                        parentType: '',
                    },
                    {
                        id: 196,
                        appWorkflowId: 93,
                        type: 'CD_PIPELINE',
                        componentId: 92,
                        parentId: 106,
                        parentType: 'CI_PIPELINE',
                    },
                    {
                        id: 200,
                        appWorkflowId: 93,
                        type: 'CD_PIPELINE',
                        componentId: 94,
                        parentId: 106,
                        parentType: 'CI_PIPELINE',
                    },
                ],
            },
        ],
    },
}

export const workflowsTrigger = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-amit-16-jan-erferf',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',
                status: DEFAULT_STATUS,
                description: 'test',
                triggerType: 'Auto',
                environmentName: '',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-dep',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsCreate = [
    {
        id: '92',
        name: 'first',
        appId: 80,
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Auto',
                environmentName: '',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                postNode: undefined,
                preNode: undefined,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsTriggerPrePostCD = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'Pre-Deployment',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                downstreams: ['CD-79'],
                type: 'PRECD',
                description: 'test',
                status: 'OK',
                triggerType: 'Auto',
                environmentId: 1,
                environmentName: '',
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-amit-16-jan-erferf',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: ['POSTCD-79'],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Auto',
                environmentName: '',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 2,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: {
                    parents: ['96'],
                    height: 126,
                    width: 200,
                    title: 'Pre-Deployment',
                    isSource: false,
                    isGitSource: false,
                    id: '79',
                    activeIn: false,
                    activeOut: false,
                    downstreams: ['CD-79'],
                    type: 'PRECD',
                    description: 'test',
                    status: 'OK',
                    triggerType: 'Auto',
                    environmentId: 1,
                    environmentName: '',
                    deploymentStrategy: 'rolling',
                    inputMaterialList: [],
                    rollbackMaterialList: [],
                    stageIndex: 1,
                    x: 0,
                    y: 0,
                    isRoot: false,
                },
                postNode: {
                    parents: ['79'],
                    height: 126,
                    width: 200,
                    title: 'Post-Deployment',
                    isSource: false,
                    isGitSource: false,
                    id: '79',
                    activeIn: false,
                    activeOut: false,
                    downstreams: [],
                    type: 'POSTCD',
                    description: 'test',
                    status: 'OK',
                    triggerType: 'Auto',
                    environmentName: '',
                    environmentId: 1,
                    deploymentStrategy: 'rolling',
                    inputMaterialList: [],
                    rollbackMaterialList: [],
                    stageIndex: 3,
                    x: 0,
                    y: 0,
                    isRoot: false,
                },
            },
            {
                parents: ['79'],
                height: 126,
                width: 200,
                title: 'Post-Deployment',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                downstreams: [],
                type: 'POSTCD',
                description: 'test',
                status: 'OK',
                triggerType: 'Auto',
                environmentName: '',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 3,
                x: 0,
                y: 0,
                isRoot: false,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-dep',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsCreatePrePostCD = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 64,
                width: 240,
                title: 'Pre-deploy, Deploy, Post-deploy',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Auto',
                environmentName: '',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 2,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: '',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const cdConfigPostResp = {
    code: 200,
    status: 'OK',
    result: {
        pipelines: [
            {
                id: 92,
                environmentId: 3,
                environmentName: 'dev2',
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-deploy',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 94,
                environmentId: 5,
                environmentName: 'dev4',
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 79,
                environmentId: 1,
                environmentName: 'dev',
                ciPipelineId: 96,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {
                    triggerType: 'AUTOMATIC',
                    name: 'Post-Deployment',
                    config: 'version: 0.0.1\ncdPipelineConf:\n  -\n    afterStages:\n      -\n        name: test-1\n        script: "date \u003e test.report\\necho \'hello\'\\n"\n        outputLocation: ./test.report\n      -\n        name: test-2\n        script: "date \u003e test2.report\\n"\n        outputLocation: ./test2.report',
                },
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 80,
                environmentId: 2,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 95,
                environmentId: 6,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
        ],
        appId: 80,
    },
}

export const cdConfigPreResp = {
    code: 200,
    status: 'OK',
    result: {
        pipelines: [
            {
                id: 92,
                environmentId: 3,
                environmentName: 'dev2',
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-deploy',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 94,
                environmentId: 5,
                environmentName: 'dev4',
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {} as CDStage,
                postStage: {} as CDStage,
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 79,
                environmentId: 1,
                environmentName: 'dev',
                ciPipelineId: 96,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {
                    triggerType: 'AUTOMATIC',
                    name: 'Pre-Deployment',
                    config: "version: 0.0.1\ncdPipelineConf:\n  -\n    beforeStages:\n      -\n        name: test-1\n        script: \"date \u003e test.report\\necho 'hello'\\n date \u003e test.report\\necho 'hello2'\\n date \u003e test.report\\necho 'hello3'\\n sleep 2m\\n\"\n        outputLocation: ./test.report",
                },
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 80,
                environmentId: 2,
                ciPipelineId: 96,
                triggerType: 'AUTOMATIC',
                description: 'test',
                name: 'amit-16-jan-replica-amit-16-jan-erferf2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
            {
                id: 95,
                environmentId: 6,
                ciPipelineId: 106,
                triggerType: 'MANUAL',
                description: 'test',
                name: 'amit-16-jan-replica-dep2',
                strategies: [
                    {
                        deploymentTemplate: 'ROLLING',
                        config: { deployment: { strategy: { rolling: { maxSurge: '25%', maxUnavailable: 1 } } } },
                        default: true,
                    },
                ],
                deploymentTemplate: 'ROLLING',
                preStage: {},
                postStage: {},
                preStageConfigMapSecretNames: { configMaps: [], secrets: [] },
                postStageConfigMapSecretNames: { configMaps: [], secrets: [] },
            },
        ],
        appId: 80,
    },
}

export const workflowsTriggerPreCDResp = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'Pre-Deployment',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                downstreams: ['CD-79'],
                type: 'PRECD',
                status: DEFAULT_STATUS,
                description: 'test',
                triggerType: 'Auto',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-amit-16-jan-erferf',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 2,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: {
                    parents: ['96'],
                    height: 126,
                    width: 200,
                    title: 'Pre-Deployment',
                    isSource: false,
                    isGitSource: false,
                    id: '79',
                    activeIn: false,
                    activeOut: false,
                    downstreams: ['CD-79'],
                    type: 'PRECD',
                    status: DEFAULT_STATUS,
                    description: 'test',
                    triggerType: 'Auto',
                    environmentName: 'dev',
                    environmentId: 1,
                    deploymentStrategy: 'rolling',
                    inputMaterialList: [],
                    rollbackMaterialList: [],
                    stageIndex: 1,
                    x: 0,
                    y: 0,
                    isRoot: false,
                },
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev2',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-dep',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev4',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsCreatePreCDResp = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 64,
                width: 240,
                title: 'Pre-deploy, Deploy',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 2,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev2',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev4',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsCreatePostCD = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 64,
                width: 240,
                title: 'Deploy, Post-deploy',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 64,
                width: 240,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev2',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 64,
                width: 240,
                title: 'Deploy',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev4',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 112,
        width: 840,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]

export const workflowsTriggerPostCD = [
    {
        id: '92',
        appId: 80,
        name: 'first',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'master',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-96'],
                type: 'GIT',
                icon: 'git',
                branch: 'master',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '96',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-amit-16-jan-ci-master-original',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['96'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-amit-16-jan-erferf',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 96,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: ['POSTCD-79'],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: {
                    parents: ['79'],
                    height: 126,
                    width: 200,
                    title: 'Post-Deployment',
                    isSource: false,
                    isGitSource: false,
                    id: '79',
                    activeIn: false,
                    activeOut: false,
                    downstreams: [],
                    type: 'POSTCD',
                    description: 'test',
                    status: DEFAULT_STATUS,
                    triggerType: 'Auto',
                    environmentName: 'dev',
                    environmentId: 1,
                    deploymentStrategy: 'rolling',
                    inputMaterialList: [],
                    rollbackMaterialList: [],
                    stageIndex: 2,
                    x: 0,
                    y: 0,
                    isRoot: false,
                },
            },
            {
                parents: ['79'],
                height: 126,
                width: 200,
                title: 'Post-Deployment',
                isSource: false,
                isGitSource: false,
                id: '79',
                activeIn: false,
                activeOut: false,
                downstreams: [],
                type: 'POSTCD',
                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Auto',
                environmentName: 'dev',
                environmentId: 1,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 2,
                x: 0,
                y: 0,
                isRoot: false,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
    {
        id: '93',
        appId: 80,
        name: 'external ci',
        nodes: [
            {
                parents: [],
                height: 64,
                width: 200,
                title: 'getting-started-nodejs',
                isSource: true,
                isRoot: true,
                isGitSource: true,
                isRegex: undefined,
                primaryBranchAfterRegex: 'test',
                regex: undefined,
                url: '',
                id: 'GIT-getting-started-nodejs-0',
                downstreams: ['CI-106'],
                type: 'GIT',
                icon: 'git',
                branch: 'test',
                sourceType: 'SOURCE_TYPE_BRANCH_FIXED',
                x: 20,
                y: 24,
            },
            {
                isSource: true,
                isGitSource: false,
                isRoot: false,
                parents: ['GIT-getting-started-nodejs-0'],
                id: '106',
                x: 280,
                y: 24,
                parentAppId: 0,
                parentCiPipeline: 0,
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-ci-arya-test',
                triggerType: 'Manual',
                status: DEFAULT_STATUS,
                type: 'CI',
                inputMaterialList: [],
                downstreams: [],
                isExternalCI: false,
                isLinkedCI: false,
                linkedCount: 0,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-deploy',
                isSource: false,
                isGitSource: false,
                id: '92',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev2',
                environmentId: 3,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
            {
                parents: ['106'],
                height: 126,
                width: 200,
                title: 'amit-16-jan-replica-dep',
                isSource: false,
                isGitSource: false,
                id: '94',
                activeIn: false,
                activeOut: false,
                connectingCiPipelineId: 106,
                deploymentAppDeleteRequest: undefined,
                parentPipelineId: 'undefined',
                parentPipelineType: undefined,
                downstreams: [],
                type: 'CD',

                description: 'test',
                status: DEFAULT_STATUS,
                triggerType: 'Manual',
                environmentName: 'dev4',
                environmentId: 5,
                deploymentStrategy: 'rolling',
                inputMaterialList: [],
                rollbackMaterialList: [],
                stageIndex: 1,
                x: 0,
                y: 0,
                isRoot: false,
                preNode: undefined,
                postNode: undefined,
            },
        ],
        startX: 0,
        startY: 0,
        height: 174,
        width: 1280,
        ciConfiguredGitMaterialId: undefined,
        approvalConfiguredIdsMap: {},
        gitMaterials: [
            {
                gitMaterialId: 80,
                materialName: 'getting-started-nodejs',
            },
        ],
    },
]
