FROM node:20-alpine AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm i

RUN pnpm --filter=web build-storybook

FROM nginx:stable

COPY --from=builder /app/apps/web/storybook-static/ /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

CMD ["/bin/bash", "-c", "nginx -g \"daemon off;\""]
EXPOSE 80
