FROM node:20-alpine AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY . .

RUN echo `git rev-parse --short HEAD` > health.html

RUN pnpm i
RUN pnpm run build:prod

FROM nginx:stable

RUN useradd -ms /bin/bash devtron

COPY --from=builder /app/apps/web/dist/ /usr/share/nginx/html
COPY --from=builder /app/apps/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/apps/web/nginx-default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY --from=builder  /app/apps/web/./env.sh .
COPY --from=builder  /app/apps/web/.env .
COPY --from=builder  /app/health.html .

RUN chown -R devtron:devtron /usr/share/nginx/html
# Make our shell script executable
RUN chmod +x env.sh
USER devtron
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]
