import { multiSelectStyles } from '@devtron-labs/devtron-fe-common-lib'

export const FILTER_STYLE = {
    ...multiSelectStyles,
    control: (base) => ({
        ...base,
        minHeight: '36px',
        fontWeight: '400',
        backgroundColor: 'var(--N50)',
        cursor: 'pointer',
    }),
    dropdownIndicator: (base) => ({
        ...base,
        padding: '0 8px',
    }),
    menuPortal: (base) => ({ ...base, zIndex: 9999 }),
}
export const HISTORY_LABEL = {
    APPLICATION: 'Application',
    ENVIRONMENT: 'Environment',
    PIPELINE: 'Pipeline',
}

export const ARTIFACTS_EMPTY_STATE_TEXTS = {
    NoFilesFound: 'No files found',
    BlobStorageNotConfigured: 'Blob storage must be configured to store any files generated by the pipeline',
    StoreFiles: 'Want to store files?',
    ConfigureBlobStorage: 'Configure blob storage',
    NoFilesGenerated: 'No files were generated by the job pipeline.',
    NoArtifactsGenerated: 'No artifacts generated',
    NoArtifactsError: 'Errr..!! We couldn’t build your code.',
}
