import { Routes } from '../../config'
import { post, get } from '../../services/api'
import { ClusterCapacityResponse, ClusterListResponse, NodeListResponse } from './types'

export const getClusterList = (): Promise<ClusterListResponse> => {
    //return get(Routes.CLUSTER_LIST)
    return Promise.resolve({
        code: 0,
        status: '',
        result: [
            {
                id: 0,
                name: 'azure-cluster',
                nodeCount: 6,
                nodeErrors: ['string', 'string'],
                nodeK8sVersions: ['1.12.6_1546'],
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
            },
            {
                id: 1,
                name: 'azure-vm',
                nodeCount: 8,
                nodeErrors: [],
                nodeK8sVersions: ['1.12.6', '1.12.3', '1.12.8'],
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
            },
            {
                id: 2,
                name: 'bayern-cluster',
                nodeCount: 14,
                nodeErrors: ['string'],
                nodeK8sVersions: ['1.12.9'],
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
            },
            {
                id: 3,
                name: 'default_cluster',
                nodeCount: 26,
                nodeErrors: ['string'],
                nodeK8sVersions: ['1.11.6_1532'],
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
            },
        ],
    })
}

export const getClusterCapacity = (): Promise<ClusterCapacityResponse> => {
    //return get(Routes.CLUSTER_CAPACITY)
    return Promise.resolve({
        code: 0,
        status: '',
        result: {
            cpu: {
                name: 'string',
                capacity: '6,503 GHz',
                allocatable: '',
                usage: '',
                request: 'string',
                limit: 'string',
                usagePercentage: '43.68',
                requestPercentage: '50.37',
                limitPercentage: '42.50',
            },
            memory: {
                name: 'string',
                capacity: '6,503 GHz',
                allocatable: '',
                usage: '',
                request: 'string',
                limit: 'string',
                usagePercentage: '38.62',
                requestPercentage: '19.08',
                limitPercentage: '27.14',
            },
        },
    })
}

export const getNodeList = (): Promise<NodeListResponse> => {
    //return get(Routes.NODE_LIST)
    return Promise.resolve({
        code: 0,
        status: '',
        result: [
            {
                name: 'ip-172-31-2-152.us-east-2.compute.internal',
                status: 'Not running',
                roles: ['Worker'],
                errors: ['string'],
                k8sVersion: '1.12.6_121',
                podCount: 21,
                taintCount: 3,
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                age: '',
            },
            {
                name: 'ip-172-31-2-152.us-east-2.compute.internal',
                status: 'Not running',
                roles: ['Worker'],
                errors: ['string'],
                k8sVersion: '1.12.6_1546',
                podCount: 13,
                taintCount: 0,
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                age: '2d',
            },
            {
                name: 'ip-172-31-2-152.us-east-2.compute.internal',
                status: 'Running',
                roles: ['Worker'],
                errors: [],
                k8sVersion: '1.12.6_1546',
                podCount: 21,
                taintCount: 3,
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                age: '8d',
            },
            {
                name: 'ip-172-31-2-152.us-east-2.compute.internal',
                status: 'Not running',
                roles: ['Worker'],
                errors: ['string'],
                k8sVersion: '1.12.6_1546',
                podCount: 21,
                taintCount: 3,
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                age: '8d',
            },
            {
                name: 'ip-172-31-2-152.us-east-2.compute.internal',
                status: 'Running',
                roles: ['Worker'],
                errors: [],
                k8sVersion: '1.12.6_1548',
                podCount: 21,
                taintCount: 0,
                cpu: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                memory: {
                    name: 'string',
                    capacity: '6,503 GHz',
                    allocatable: '',
                    usage: '',
                    request: 'string',
                    limit: 'string',
                    usagePercentage: '',
                    requestPercentage: '',
                    limitPercentage: '',
                },
                age: '24h',
            },
        ],
    })
}

export const getNodeCapacity = (): Promise<any> => {
    return get(Routes.NODE_CAPACITY)
}
